#!/usr/bin/env python3
"""Convert a checkpoint to a quantization that gfx90a actually accelerates.

    model-convert /models/my-model                 ask, then generate
    model-convert https://huggingface.co/Org/M --to W4A16 --out /models/m-w4a16
    model-convert /models/my-model --to W8A8 --out /out --run

Without --run it writes a complete, runnable llm-compressor script and stops,
so the recipe can be read and edited before anything spends GPU hours. With
--run it executes that same script -- the file on disk is exactly what ran.

Quantizing is not free: it needs the weights, a calibration pass on the GPU,
and time proportional to model size. This tool does not hide that.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from typing import NoReturn

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mi210_fastpath import RESET, BOLD, GREEN, YELLOW, DIM, facts, load_config  # noqa: E402

# What CDNA2 can actually accelerate. FP8 is deliberately absent: MI210 has no
# FP8 datapath, so converting to it buys nothing here however popular it is.
SCHEMES = {
    "W4A16": {
        "blurb": "4-bit weights, 16-bit activations. Biggest VRAM saving.",
        "modifier": "GPTQModifier",
        "moe_bonus": (
            "On a MoE checkpoint this is the one that hits the int4 interleave "
            "path this image widens to GFX9 (1.45-4.8x on the int4 MoE kernel, "
            "bit-identical)."
        ),
    },
    "W8A8": {
        "blurb": "8-bit weights and activations, int8. Less compression, closer to bf16 quality.",
        "modifier": "GPTQModifier",
        "moe_bonus": "",
    },
}


def die(msg: str) -> NoReturn:
    print(f"error: {msg}", file=sys.stderr)
    raise SystemExit(2)


def recommend(f: dict) -> tuple[str, list[str]]:
    """Pick a default scheme and say why, from what this project measured."""
    why: list[str] = []
    is_moe = bool(f["experts"])
    method = f["quant_method"]

    if method and ("fp8" in method or "fp8" in (f["quant_fmt"] or "")):
        why.append(
            "Source is FP8, which MI210 (CDNA2) has no datapath for -- converting "
            "to an int format is the point of this run."
        )
    elif method:
        why.append(f"Source is already {method} {f['quant_bits'] or ''}-bit.")

    if is_moe:
        why.append(
            "This is a MoE checkpoint, and W4A16 in compressed-tensors format is "
            "the only path that reaches the int4 interleave kernel."
        )
        return "W4A16", why

    why.append(
        "Dense model: W4A16 maximises the VRAM saved; W8A8 keeps more quality "
        "at a larger footprint. Neither has a measured throughput number on this "
        "hardware, so pick on memory, not speed."
    )
    return "W4A16", why


def ignore_list(f: dict) -> list[str]:
    """Layers that must stay unquantised.

    The MoE router is the one that bites: quantising the gate wrecks expert
    selection, and the failure is a quality drop rather than an error.
    """
    ig = ["lm_head"]
    if f["experts"]:
        ig += ["re:.*mlp.gate$", "re:.*mlp.shared_expert_gate$"]
    return ig


SCRIPT = '''#!/usr/bin/env python3
"""Generated by model-convert. This file is exactly what runs -- edit freely.

  source : {src}
  scheme : {scheme}
  output : {out}
"""
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer

from llmcompressor import oneshot
from llmcompressor.modifiers.quantization import GPTQModifier

SOURCE = {src!r}
OUTPUT = {out!r}
SCHEME = {scheme!r}
NUM_CALIBRATION_SAMPLES = {samples}
MAX_SEQ_LENGTH = {seqlen}

# The router must not be quantised: expert selection degrades quietly rather
# than failing, so this is a correctness setting, not a tuning one.
IGNORE = {ignore!r}

tokenizer = AutoTokenizer.from_pretrained(SOURCE, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    SOURCE, torch_dtype="auto", device_map="auto", trust_remote_code=True
)

ds = load_dataset({dataset!r}, split={split!r})
ds = ds.shuffle(seed=42).select(range(min(NUM_CALIBRATION_SAMPLES, len(ds))))


def preprocess(example):
    messages = example.get("messages") or example.get("conversation")
    if messages:
        text = tokenizer.apply_chat_template(messages, tokenize=False)
    else:
        text = example.get("text") or example.get("output") or ""
    return tokenizer(text, truncation=True, max_length=MAX_SEQ_LENGTH, padding=False)


ds = ds.map(preprocess, remove_columns=ds.column_names)

oneshot(
    model=model,
    dataset=ds,
    recipe=GPTQModifier(targets="Linear", scheme=SCHEME, ignore=IGNORE),
    output_dir=OUTPUT,
    max_seq_length=MAX_SEQ_LENGTH,
    num_calibration_samples=NUM_CALIBRATION_SAMPLES,
)
tokenizer.save_pretrained(OUTPUT)
print("wrote", OUTPUT)
'''


def main() -> int:
    ap = argparse.ArgumentParser(
        prog="model-convert",
        description="Convert a checkpoint to a quantization gfx90a accelerates.",
    )
    ap.add_argument("model", help="local directory, HF repo id, or Hub URL")
    ap.add_argument("--to", choices=sorted(SCHEMES), help="target scheme")
    ap.add_argument("--out", help="output directory")
    ap.add_argument("--run", action="store_true", help="execute, not just generate")
    ap.add_argument("--samples", type=int, default=512, help="calibration samples")
    ap.add_argument("--seqlen", type=int, default=2048, help="calibration sequence length")
    ap.add_argument("--dataset", default="HuggingFaceH4/ultrachat_200k")
    ap.add_argument("--split", default="train_sft")
    ap.add_argument("-y", "--yes", action="store_true", help="accept the recommendation")
    a = ap.parse_args()

    cfg, _config_path = load_config(a.model)
    f = facts(cfg)
    default, why = recommend(f)

    print(f"{BOLD}{a.model}{RESET}")
    print(
        f"  {f['model_type']}  hidden {f['hidden']}  "
        f"{'MoE, ' + str(f['experts']) + ' experts' if f['experts'] else 'dense'}  "
        f"quant {f['quant_method'] or 'none'}"
    )
    print()
    for w in why:
        print(f"  - {w}")
    print()

    scheme = a.to
    if not scheme:
        if a.yes or not sys.stdin.isatty():
            scheme = default
            print(f"{GREEN}scheme:{RESET} {scheme} (recommended)")
        else:
            opts = sorted(SCHEMES)
            print(f"{BOLD}target scheme{RESET}")
            for i, s in enumerate(opts, 1):
                mark = "  (recommended)" if s == default else ""
                print(f"  {i}) {s:6s} {SCHEMES[s]['blurb']}{mark}")
                if s == default and SCHEMES[s]["moe_bonus"]:
                    print(f"     {DIM}{SCHEMES[s]['moe_bonus']}{RESET}")
            try:
                pick = input(f"\nchoice [1-{len(opts)}, enter for {default}]: ").strip()
            except EOFError:
                pick = ""
            scheme = default if not pick else opts[int(pick) - 1] if pick.isdigit() else pick
            if scheme not in SCHEMES:
                die(f"unknown scheme {scheme!r}")

    out = a.out or f"{a.model.rstrip('/')}-{scheme.lower()}"
    if not os.path.isabs(out) and not os.path.isdir(os.path.dirname(out) or "."):
        out = os.path.join(os.getcwd(), os.path.basename(out))

    script = SCRIPT.format(
        src=a.model, out=out, scheme=scheme, samples=a.samples, seqlen=a.seqlen,
        ignore=ignore_list(f), dataset=a.dataset, split=a.split,
    )
    os.makedirs(out, exist_ok=True)
    path = os.path.join(out, "quantize.py")
    with open(path, "w") as fh:
        fh.write(script)
    os.chmod(path, 0o755)

    print()
    print(f"{GREEN}wrote{RESET} {path}")
    print(f"  scheme  {scheme}")
    print(f"  ignore  {', '.join(ignore_list(f))}")
    print(f"  calib   {a.samples} samples x {a.seqlen} tokens from {a.dataset}")

    if not a.run:
        print()
        print("Review it, then run:")
        print(f"  model-convert {a.model} --to {scheme} --out {out} --run")
        print(f"  {DIM}or: python3 {path}{RESET}")
        return 0

    try:
        import llmcompressor  # noqa: F401
    except ImportError:
        die(
            "llmcompressor is not in this image, so nothing was converted.\n"
            "\n"
            "  It is deliberately absent, and as of 2026-08-04 it cannot be added:\n"
            "    - it installs but does not import on this base image's Python 3.14\n"
            "      (pydantic 2.13.4 fails to evaluate 'dict[str, Any]');\n"
            "    - installing it downgrades transformers 5.14.0 -> 5.10.1 and moves\n"
            "      compressed-tensors past vllm's ==0.17.0 pin.\n"
            "\n"
            f"  The script just written is standalone -- run it anywhere llm-compressor\n"
            f"  works, GPU included:  python3 {path}\n"
            "  ./build/add-convert.sh re-checks both conditions if you want to retry."
        )

    print()
    print(f"{YELLOW}running{RESET} -- this needs the GPU and scales with model size")
    sys.stdout.flush()
    return subprocess.call([sys.executable, path])


if __name__ == "__main__":
    raise SystemExit(main())
